app:
  file:
    location:
      cv: D:\cv
  portal-urL: http://fjb01.winzone.vn

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ims
    username: root
    password: Long0347647117
  jpa:
    hibernate:
      ddl-auto: update
    # show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: hn24pjb03group2fev2@gmail.com
    password: plap asxl itnw uhrz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
